/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example

import kotlin.time.measureTime
import uniffi.uniffi_tests.add
import jdk.incubator.foreign.*
import java.lang.invoke.MethodType
import java.lang.invoke.MethodHandle
import java.nio.file.Paths

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    var timeTaken = measureTime {
        repeat(1000000) {
            add(5u, 7u)
	}
    }
    println("add 1,000,000 times timeTaken $timeTaken") 

    val path = Paths.get("").toAbsolutePath().toString()       
    System.load(path + "/libuniffi_tests.so")
    var add_func = SymbolLookup.loaderLookup().lookup("uniffi_uniffi_tests_fn_func_add").get()
    var method_type = MethodType.methodType(Int::class.java, Int::class.java, Int::class.java)
    var func_desc = FunctionDescriptor.of(CLinker.C_INT, CLinker.C_INT, CLinker.C_INT)
    var add_fast = CLinker.getInstance().downcallHandle(add_func, method_type, func_desc)

    val v1: Int = 5
    val v2: Int = 7

    var add_total_2 = 0
    timeTaken = measureTime {
        repeat(1000000) {
            add_total_2 += add_fast(v1, v2) as kotlin.Int
	}
    }
    println("add_fast 1,000,000 times timeTaken $timeTaken") 
    println(add_total_2)
}
